"""make_meeting_id_nullable

Revision ID: e23aa984f770
Revises: f2faadc67357
Create Date: 2026-07-23 14:50:13.475135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23aa984f770'
down_revision: Union[str, Sequence[str], None] = 'f2faadc67357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_chunks', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meeting_clips', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('meeting_clips_meeting_id_fkey'), 'meeting_clips', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_clips', 'meetings', ['meeting_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting_clips', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_clips_meeting_id_fkey'), 'meeting_clips', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.alter_column('meeting_clips', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meeting_chunks', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
