"""add_meeting_clips

Revision ID: f2faadc67357
Revises: 395a1482e312
Create Date: 2026-07-23 12:13:14.043859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2faadc67357'
down_revision: Union[str, Sequence[str], None] = '395a1482e312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('transcript_raw', sa.Text(), nullable=True),
    sa.Column('transcript_clean', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_clips_id'), 'meeting_clips', ['id'], unique=False)
    op.add_column('meeting_chunks', sa.Column('clip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meeting_chunks', 'meeting_clips', ['clip_id'], ['id'], ondelete='CASCADE')
    op.alter_column('meetings', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_constraint(None, 'meeting_chunks', type_='foreignkey')
    op.drop_column('meeting_chunks', 'clip_id')
    op.drop_index(op.f('ix_meeting_clips_id'), table_name='meeting_clips')
    op.drop_table('meeting_clips')
    # ### end Alembic commands ###
